# Inserção de dados...
print ("---------------------------------------")
print ("Digite seu nome:")
MyName = str (input())
print ("Digite sua idade:")
MyAge = int (input())
print ("Digite sua altura")
MyHeight = float (input ())
print ("Digite sua localização")
MyLocation = str (input())
print ("Qual e o seu idioma?")
MyLanguage = str (input ())
print ("Qual e o seu genero?")
MyGender = str (input ())
print ("Qual e a sua comida favorita? ")
MyFoodFav = str (input ())

# Exibição do conteúdo das variaveis...
print ("Prazer! ", MyName )
print ("Sua idade é: ", MyAge )
print ("Sua altura é: ", MyHeight, "metros" )
print ("Então você e de: ", MyLocation )
print ("Você fala: ", MyLanguage )
print ("Seu genero é: ", MyGender)
print ("Sua comida favorita é: ", MyFoodFav)
print ("---------------------------------------")